### PR TITLE
Backporting changes from yt/analysis_modules

### PR DESCRIPTION
**Pull request by brittonsmith**
This should backport all outstanding changes made to yt's analysis_modules.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Looks like h5py/hdf5 needs to be installed on travis? There are also some MPI errors that may be related to h5py being missing.

**Comment by ngoldbaum** [comment]
Triggered another test run now that the other PR is merged.

**Comment by brittonsmith** [comment]
Ah, I missed a merger conflict.  Will fix.

**Comment by brittonsmith** [comment]
The tests are all passing except for missing answers for the new light cone tests. I'll need to update the gold standard tag for that. I also realize that we can now allow the rockstar tests to run on Python 3 again, which will also require a gold standard update. I will just include that in this PR so we only have to do it once.

**Comment by brittonsmith** [comment]
I'm going to update the gold standard in this PR now.

**Comment by brittonsmith** [comment]
Ok, I think this is good to go.

**Pull request merged**
