### PR TITLE
BLD: switch to Cython 3.0, forbid deprecated Numpy C API in generated code

### PR DESCRIPTION
**Pull request by neutrinoceros**
Opening as a draft. Build already works (locally) but there may be some performance regressions. Hopefully it'll show in CI.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Tests are not taking longer than usual, so I think this is good to go ?
@matthewturk , would you advise slapping `noexcept` on every `nogil` function anyway ?

**Comment by brittonsmith** [comment]
I'm ok with this going in, but I don't have enough expertise in cython to comment on the question raised.

**Review by brittonsmith — APPROVED** [review]

**Comment by matthewturk** [comment]
I would advise that, yeah.  But it's probably not strictly necessary.

**Comment by neutrinoceros** [comment]
ok done. I'll merge this and follow-up PRs when tests pass. Thank you both !

**Comment by neutrinoceros** [comment]
actually, this is causing compilation errors in CI, so I've reverted this part of the patch. Let's just keep in mind that this change may be the first suspect in the event of performance regressions in the near future.

**Pull request merged**
