### PR TITLE
Adding an outer_radius parameter to the iterative COM callback

### PR DESCRIPTION
**Pull request by chummels**
I found this new parameter to be necessary to get consistent results in the HOP finder on some of my datasets to avoid the algorithm centering on other halos.

### CODE REVIEW

**Comment by brittonsmith** [comment]
I think you'll need to rebase with `master` for the tests to pass.

**Comment by ngoldbaum** [comment]
What git commands did you run? Usually when I rebase a branch on master I do something like:

```
git checkout master
git pull upstream master
git checkout mybranch
git rebase master
```

You can use the git reflog to go back to the state of the repo before the rebase, you might need to force-move the branch back.

You might also find ohshitgit.com helpful...

If all else fails you could cherry-pick you commits one by one on top of the current master branch and just open a new PR.

**Comment by chummels** [comment]
Your list of commands is what I did.  I then realized that there was trailing whitespace on two of the lines of comments, so I added an additional commit correcting that before it got flagged by the flake tests.  And this ended up with the current state of affairs.  

I guess I can just open a new PR, but I'm not sure how to fix the state of the github repo short of just deleting and re-creating it.

**Comment by ngoldbaum** [comment]
Just abandon the branch? You don't actually need to do that, I just don't know the git incantations offhand to fix the current state of the PR.

**Comment by ngoldbaum** [comment]
Also in the future, merging is safer than rebasing if you're not comfortable with rebasing.

**Comment by brittonsmith** [comment]
The last test failure was because the cached test answers were out of date. I cleared the cache and restarted them and they appear to be passing now. I've seen situations like this before, where the PR includes changes that should already be in `master` and it usually works fine. I think it should still be ok to merge this.

**Comment by ngoldbaum** [comment]
Ah good deal!

**Pull request merged**
