### PR TITLE
PPVCube for yt-4.0

### PR DESCRIPTION
**Pull request by jzuhone**
This PR incorporates changes which are necessary to get `PPVCube` compatible with yt-4.0. Most of these have to do with changes to FITS file writing, as well as using `sampling_type="local"` so that SPH datasets will also work.

### CODE REVIEW

**Comment by jzuhone** [comment]
@brittonsmith the tests will automatically fail because I've got yt-4.0 as the minimum version in the `yt-4.0` branch that this would merge into. Maybe I could try fixing the tests first.

**Comment by brittonsmith** [comment]
@jzuhone, setting up testing for the yt-4.0 branch is a good idea. I think you should have permissions for circleci, but let me know if not.

**Comment by brittonsmith** [comment]
BTW, the PR itself looks fine to me. We can merge this whenever, but waiting until after tests are working is fine with me.

**Comment by brittonsmith** [comment]
@jzuhone, it looks like the `install_requires` of `yt>=4.0` isn't satisfiable by how yt-4.0 currently lists its version, `4.0.dev0`. It's probably safe to relax that in `setup.py` for now.

**Comment by jzuhone** [comment]
Yeah, I'm hoping to come back to this soon.

**Pull request closed without merging**
