### PR TITLE
TST: test on Python 3.11

### PR DESCRIPTION
**Pull request by neutrinoceros**
My goal here is to start testing on Python 3.11
I except this will be a little challenging because:
- at the moment, h5py hasn't released wheels for it yet
- the auto conda-forge PR is currently failing builds https://github.com/conda-forge/yt_astro_analysis-feedstock/pull/12?notification_referrer_id=NT_kwDOANbIErM1MDYxNjc0NzU1OjE0MDc1OTIy#issuecomment-1346018316

### CODE REVIEW

**Comment by neutrinoceros** [comment]
So, the state of affairs currently is that builds fail at compile time, but unfortunately it fails even sooner on my machine because I can't even install h5py from source on macOS. Currently I don't think I'll be able to disentangle this before wheels are available for h5py + Python 3.11

**Comment by neutrinoceros** [comment]
Appears to be a linking problem
```
io/io_tipsy.c:7:10: fatal error: rpc/types.h: No such file or directory
    7 | #include <rpc/types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
```

**Comment by neutrinoceros** [comment]
Another problem I'm seeing locally (turns out I can try and compile with `python -m build`) is that numpy 1.23, the oldest version supporting Python 3.11, removes some C API we rely on (namely `NPY_ARRAY_UPDATEIFCOPY`)
https://numpy.org/doc/stable/release/1.23.0-notes.html?highlight=npy_array_updateifcopy#expired-deprecations

Maybe I can try to fix this first, since I can iterate locally

**Comment by neutrinoceros** [comment]
Wheels are setup, but the linking problem on circleci is still here. I've tried to reinstall the "missing" header files via `libntirpc-dev`, `libtirpc-dev` and `libgcc-dev` packages, for now nothing worked.

**Comment by neutrinoceros** [comment]
The more I think about it the less I understand this failure; it must be a problem with the docker image that's used for Python 3.11, and the right call is probably just to report to CircleCI directly.

**Comment by neutrinoceros** [comment]
Following an exchange with CircleCI's support, here's the report upstream https://github.com/CircleCI-Public/cimg-base/issues/226

**Comment by neutrinoceros** [comment]
I intend to take the important bits from this into the next bugfix release but not necessarily the whole thing

**Comment by neutrinoceros** [comment]
h5py doesn't even compile from source anymore. The repo seems quite active these days so I'll try again soon

**Comment by neutrinoceros** [comment]
So there are two main difficulties with testing on Python 3.11 with Circle CI:
- The corresponding docker image is using Ubuntu 22.04, and compiling rockstar there requires a couple patches to its Makefile. I think this part is now working correctly but it's nonetheless worrisome because rockstar didn't receive any update in the last two years and no merge request was ever reviewed or merged, so I have little hope of upstreaming the patch, and I expect it will not get better in the future.
- `h5py` still doesn't have wheels for Python 3.11. I thought I could workaround this by building it from source but it's actually a very complicated process to replicate so I figure it's not worth it. I'll just wait some more.

**Comment by jzuhone** [comment]
@brittonsmith any chance we can move this repo to github actions?

**Comment by neutrinoceros** [comment]
@jzuhone AFAIC feel free to give it a shot, but it won't help with the current blocker

**Comment by neutrinoceros** [comment]
h5py 3.8 was just released with 3.11 wheels, let's give this another shot !

**Comment by neutrinoceros** [comment]
closing/reopening doesn't retrigger circleci, so I'll force-push instead

**Comment by neutrinoceros** [comment]
This is now stable, I'll include it in a bugfix release

**Comment by brittonsmith** [comment]
@jzuhone, I have no objections to moving the testing to actions, but also no bandwidth to do it. I'm more than happy for it to happen if you'd like to give it a try.

@neutrinoceros, as far as I understand, the main repo of rockstar-galaxies will never be updated again. It's even missing a crucial, but minor bugfix that only exists in [John Wise's repo](https://bitbucket.org/jwise77/rockstar-galaxies). This is noted in the yt-astro install docs. Previously, yt-project maintained an older version of rockstar for similar reasons. I would prefer not to have to do that. Maybe the new "upsteam" could be John's repo. I'm pretty sure he would accept pull requests.

**Pull request merged**
