### PR TITLE
Backporting from yt

### PR DESCRIPTION
**Pull request by brittonsmith**

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Looks like that changed some test answers:

```
======================================================================
FAIL: LightConeProjection_32Mpc_32_enzo_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/yt-project/yt_astro_analysis/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/yt-git/yt/utilities/answer_testing/framework.py", line 392, in __call__
    self.compare(nv, ov)
  File "/home/travis/build/yt-project/yt_astro_analysis/yt_astro_analysis/cosmological_observation/light_cone/tests/test_light_cone.py", line 79, in compare
    assert_equal(new_result, old_result, verbose=True)
  File "/home/travis/build/yt-project/yt_astro_analysis/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 296, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/home/travis/build/yt-project/yt_astro_analysis/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 787, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/travis/build/yt-project/yt_astro_analysis/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal
(mismatch 100.0%)
 x: array([  5.974790e-05,   1.133650e-05,   8.970763e-02])
 y: array([  1.107059e-06,   1.002082e-07,   2.580261e-04])
>>  raise AssertionError('\nArrays are not equal\n\n(mismatch 100.0%)\n x: array([  5.974790e-05,   1.133650e-05,   8.970763e-02])\n y: array([  1.107059e-06,   1.002082e-07,   2.580261e-04])')
```

**Comment by brittonsmith** [comment]
I'll inspect this manually in the next day or so.

**Comment by brittonsmith** [comment]
I've convinced myself that the new answers are correct and the old ones were wrong. The change in the answers has to do with the fact that `obj['x']` returns CGS units and `obj['index', 'x']` returns `code_length`. The values they are being compared against are most closely related to `code_length`, which is why this change fixes things. Technically, the units should be `unitary`, but I think we can fix that another time. This code is long overdue for at least a minor overhaul.

**Comment by brittonsmith** [comment]
For now, I will update the gold standard so the tests can pass here and create an issue to make note of the work that will need to happen in the future.

**Pull request merged**
